#!/bin/bash -ex
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

sudo apt-get update

cd ~

wget https://github.com/nanopool/Claymore-Dual-Miner/releases/download/v9.5/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v9.5.-.LINUX.tar.gz

sudo mkdir /usr/local/claymore95
sudo tar -xvf Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v9.5.-.LINUX.tar.gz -C /usr/local/claymore95

cd /usr/local/claymore95
sudo chmod u+s ethdcrminer64

echo "#!/bin/sh
export GPU_MAX_ALLOC_PERCENT=100
./ethdcrminer64 -epool us2.ethermine.org:14444  -ewal  0x83878e9ACF5BC3f37aE7f26C9947aF04b08B35DB.FranksAWS  -epsw x -mode 1 -tt 68 -allpools 1" >> mine.sh

sudo chmod +x mine.sh

./mine.sh
