#!/bin/bash
# Normally would start with an yum update -y && yum upgrade -y but these instances
# are ephermeral and have no inbound ports open to 0.0.0.0/0. Although there
# is still inherent risk waiting for instance to update is a waste of time.
#
# p2 GPU instances have some special optimizations to squeeze out a bit more performance.
# Reference: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html#optimize_gpu

getgputype=$(nvidia-smi -q | grep 'Product Brand' | awk '{ print $4 }')
if [ $getgputype == "Tesla" ];then
nvidia-smi -pm 1
nvidia-smi --auto-boost-default=0
nvidia-smi -ac 2505,875
else
	echo "Not a p2 instance."
fi

# 
# Next, prepare and make the Monero minerd miner. This miner will use the CPU.
nocpus=$(cat /proc/cpuinfo | grep processor | wc -l)
sudo apt-get update
sudo apt-get install -y automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++ autotools-dev
git clone https://github.com/wolf9466/cpuminer-multi              
cd /cpuminer-multi
sudo chmod +x ./autogen.sh
sudo ./autogen.sh
sudo CFLAGS="-march=native" ./configure
make
cd ..
###########################################################################################
# Instructions for Monero mining at mineXMR.com here: http://minexmr.com/#getting_started #
###########################################################################################
## sudo /cpuminer-multi/minerd -a cryptonight -o stratum+tcp://mine.moneropool.com:3333 -u 48JoGrnYz1M3Vi5Bo2xzYVX4zMwsCFRe4Hch5WNhc9qjS1TMK79kQiZhUeiYHwrxakXNiUhDtaw2BU4bPZVS1egeE2dswvg -p pecnikdc@gmail.com -t $(cat /proc/cpuinfo | grep processor | wc -l)
sudo /cpuminer-multi/minerd -a cryptonight -o stratum+tcp://mine.moneropool.com:3333 -u 48JoGrnYz1M3Vi5Bo2xzYVX4zMwsCFRe4Hch5WNhc9qjS1TMK79kQiZhUeiYHwrxakXNiUhDtaw2BU4bPZVS1egeE2dswvg -p pecnikdc@gmail.com -t $nocpus
